language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t n23space/docker-react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true n23space/docker-react-test npm test -- --coverage

after_success:
    - docker build -t n23space/docker-react-client ./client
    - docker build -t n23space/docker-react-nginx ./nginx
    - docker build -t n23space/docker-react-server ./server
    - docker build -t n23space/docker-react-worker ./worker
    # log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images and push to docker hub
    - docker push n23space/docker-react-client
    - docker push n23space/docker-react-nginx
    - docker push n23space/docker-react-server
    - docker push n23space/docker-react-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-3
    app: React-Docker-App
    env: ReactDockerApp-env
    bucket_name: elasticbeanstalk-eu-west-3-128565263003
    bucket_path: docker-react
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

